version: '3'
services:
  nginx:
    build:
      context: ./nginx
    container_name: lumen_nginx
    volumes:
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf
      - ../lumen-app:/var/www/lumen
    ports:
      - "8000:80"
    links:
      - lumen
  lumen:
    volumes:
      - ../lumen-app:/var/www/lumen
  mysql:
    build:
      context: ./mysql
    container_name: lumen_mysql
    volumes:
      - ./data-volumes/mysql/var-lib-mysql:/var/lib/mysql
    env_file: .env
    ports:
      - "13306:3306"
  redis:
    image: redis:latest
    container_name: lumen_redis
    volumes:
      - ./data-volumes/redis/data:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes